from random import choice
d = {
    'LBEF stands for': 'Lord Buddha Education Foundation',
    'Python was developed by': 'Guido van Rossum',
    'Keyword used to create a function in Python': 'def',
    'Capital of Nepal': 'Kathmandu',
    'Capital of India': 'New Delhi',
    'Capital of Japan': 'Tokyo',
    'Capital of France': 'Paris',
    'Capital of Australia': 'Canberra',
    'Largest planet in the Solar System': 'Jupiter',
    'Smallest planet in the Solar System': 'Mercury',
    'The Red Planet is': 'Mars',
    'The Sun is a': 'Star',
    'Earth has how many moons': '1',
    'The chemical symbol of water': 'H2O',
    'The chemical symbol of gold': 'Au',
    'The chemical symbol of oxygen': 'O',
    'The chemical symbol of sodium': 'Na',
    'The hardest natural substance': 'Diamond',
    'The process by which plants make food': 'Photosynthesis',
    'The largest ocean on Earth': 'Pacific Ocean',
    'The longest river in the world': 'Nile River',
    'The highest mountain in the world': 'Mount Everest',
    'Mount Everest is located in': 'Nepal',
    'The national animal of Nepal': 'Cow',
    'The national flower of Nepal': 'Rhododendron',
    'The national bird of Nepal': 'Danphe',
    'The currency of Nepal': 'Nepalese Rupee',
    'The currency of the USA': 'US Dollar',
    'The currency of Japan': 'Yen',
    'The inventor of the telephone': 'Alexander Graham Bell',
    'The inventor of the light bulb': 'Thomas Edison',
    'The father of computers': 'Charles Babbage',
    'The founder of Microsoft': 'Bill Gates',
    'The founder of Apple': 'Steve Jobs',
    'The founder of Facebook': 'Mark Zuckerberg',
    'The founder of Tesla': 'Elon Musk',
    'Python is a': 'Programming Language',
    'HTML stands for': 'HyperText Markup Language',
    'CSS stands for': 'Cascading Style Sheets',
    'CPU stands for': 'Central Processing Unit',
    'RAM stands for': 'Random Access Memory',
    'ROM stands for': 'Read Only Memory',
    'USB stands for': 'Universal Serial Bus',
    'IP stands for': 'Internet Protocol',
    'WWW stands for': 'World Wide Web',
    'HTTP stands for': 'HyperText Transfer Protocol',
    'HTTPS stands for': 'HyperText Transfer Protocol Secure',
    'AI stands for': 'Artificial Intelligence',
    'ML stands for': 'Machine Learning',
    'The first computer programmer': 'Ada Lovelace',
    'Binary number system uses digits': '0 and 1',
    'Decimal number system uses digits': '0 to 9',
    'The largest continent': 'Asia',
    'The smallest continent': 'Australia',
    'The largest desert in the world': 'Antarctica',
    'The hottest planet in the Solar System': 'Venus',
    'The fastest land animal': 'Cheetah',
    'The largest mammal': 'Blue Whale',
    'The tallest animal': 'Giraffe',
    'The king of the jungle': 'Lion',
    'The national sport of Nepal': 'Volleyball',
    'The first Prime Minister of Nepal': 'Bhimsen Thapa',
    'The first President of Nepal': 'Ram Baran Yadav',
    'The current federal system of Nepal started in': '2015',
    'The first man on the Moon': 'Neil Armstrong',
    'The first woman in space': 'Valentina Tereshkova',
    'The first country to land on the Moon': 'United States',
    'The speed of light is approximately': '300000 km/s',
    'The boiling point of water in Celsius': '100',
    'The freezing point of water in Celsius': '0',
    'The SI unit of force': 'Newton',
    'The SI unit of energy': 'Joule',
    'The SI unit of power': 'Watt',
    'The SI unit of current': 'Ampere',
    'The SI unit of temperature': 'Kelvin',
    'The SI unit of length': 'Meter',
    'The SI unit of mass': 'Kilogram',
    'The SI unit of time': 'Second',
    'The author of Harry Potter': 'J K Rowling',
    'The author of Romeo and Juliet': 'William Shakespeare',
    'The author of Muna Madan': 'Laxmi Prasad Devkota',
    'The national poet of Nepal': 'Laxmi Prasad Devkota',
    'The language primarily spoken in Nepal': 'Nepali',
    'The official language of Brazil': 'Portuguese',
    'The official language of China': 'Mandarin Chinese',
    'The official language of Japan': 'Japanese',
    'The official language of France': 'French',
    'The official language of Germany': 'German',
    'The first search engine on the web': 'Archie',
    'The most popular search engine': 'Google',
    'The operating system developed by Microsoft': 'Windows',
    'The operating system developed by Apple': 'macOS',
    'The mascot of Python programming language': 'Python Snake',
    'The version control system widely used in software development': 'Git',
    'The platform used to host Git repositories': 'GitHub',
    'The company that developed ChatGPT': 'OpenAI',
    'The current Secretary-General of the United Nations': 'Antonio Guterres',
    'The headquarters of the United Nations': 'New York City'
}
questions_set=list(d.keys())
marks=0
for x in range(5):
    question=choice(questions_set)
    questions_set.remove(question)
    print(f'{x+1}. {question}: ')
    answer=input('Answer: ')

    if answer.lower()==d[question].lower():
        print('Congratulation!!!')
        marks+=2
    else:
       print('Sorry!! Try again') 

print(f'Total Marks Scored: {marks}')
